### ISSUE TITLE
Add compiled files and project files to .gitignore

### ISSUE THREAD

**Issue by MoMenne** [jesseneff/mario#1]
Hey, here's a pretty easy / minor thing to take a look at.

So there is a general maxim that if the file is consistently re-generated then it should be left out of version control.  The two big categories this usually applies to are project files and compiled files.  

Project files are important to ignore because they are generated and often contain hard coded local file paths in the text.  

The other item are the compiled files (in the out directory).  These files change everytime you run the program and therefore should also not be included in version control.

**Comment by MoMenne** [comment]
Oops.  Nevermind!  I just looked at your most recent repo

**Comment by MoMenne** [comment]
Yeah actually take a look at this as well

**Comment by jesseneff** [comment]
Removed all binaries and project files from all branches. Thank you!
