### ISSUE TITLE
Factory Pattern should hide Printer instantiation

### ISSUE THREAD

**Issue by MoMenne** [jesseneff/mario#2]
Hey Nathan,

Great looking code.  Good job.  You nailed the subtleties that a lot of people miss on the early home work assignments.  The code is well organized.  I really like that you pass Pyramid to printer and that you use toString; that shows great understanding.  You nailed the interfaces (File and Console Printer) and you even used correct Java 7+ syntax by using the try-with-resources on reading the file.

There is one improvement that I would suggest.  Use the FactoryPattern to hide the instantiation of your printers.  The Factory should allow you to "hide" the word "new" in your Main class when creating your Console or File Strategy. (i.e. something like that OutputStrategy printer = OutputFactory.filePrinter();)

This allows you to decouple from the ConsoleStrategy and FileStrategy classes.  If you ever needed to swap one of those classes out.  You could stay true to the [open close principle](https://en.wikipedia.org/wiki/Open/closed_principle) and create a Strategy implementation and swap it out in the factory... then you never have to touch the more intricate code in the Main class.

Overall, your code looks great.  Keep up the good work.  You're about half way through and you're getting to the really fun stuff.

Cheers,
Mike

**Comment by jesseneff** [comment]
I got the program decoupled from those strategy classes. I'm not 100% on if this is a good way of implementing the factory pattern with interfaces. Let me know what you think.
